### ISSUE TITLE
Replace CloudFoundry command line usage with use of API

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#58] opened 2018-02-23 16:58 UTC
`CommandLineCloudFoundryDeployer` is not safe for multiple concurrent use. Should reimplement the `Deployer` interface using the CF API.

**Comment by claymccoy** [comment] 2018-03-07 20:42
Looking into this today and it seems unnecessarily complicated to pull this off. Just like everyone, we use the CLI to `cf push`. It turns out that push is a high level concept that has no direct equivalent in the more granular API. There is no documentation about how to do something equivalent in the API.

I found some hints. In [this closed issue](https://github.com/cloudfoundry/cli/issues/525) some other people are trying to do something similar to push using the API with some success.
It is a little discouraging to see this from @goehmen though:
"cf push is complex and is not something we recommend recreating via API"
So what use is the API then?

[Another place mentions](https://www.pivotaltracker.com/n/projects/892938/stories/78235856) some steps that make up a push:
* find and validate app to push - cf validate-for-push
* refresh auth token - prob no demand
* creates or updates app with app params -
* creates/updates routes for app
* uploads the app bits (could decomp diff kinds of uploading)
* if svcs, binds app to svcs
* restarts the app

There are various npm cloud foundry clients, but they have various states of maturity. None of them try to implement a push.

There is a java cloud foundry client, which does [implement push](https://github.com/cloudfoundry/cf-java-client/blob/7e84e8d11735a883befa94cd7e469e1a21253b0e/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L352).
But we don't have a java atomist client to use this in.

So I could create a small Java service that uses the java cloud foundry client and our ts automation uses it. That is more moving parts than I would like though.
Or I can look at the various hints above and reverse engineer a push using the API even though it is discouraged. I think I'll try this first.

**Comment by ddgenome** [comment] 2018-03-07 21:47
It's probably better and easier to just make running `cf push` safe for "multiple concurrent use", whatever the issue is there. Perhaps just not used cached checkouts?

**Comment by cdupuis** [comment] 2018-03-08 10:59
> Perhaps just not used cached checkouts? 

The concurrency problems here has nothing to do with _cached checkouts_ but rather with the fact that the CF CLI stores the credentials in a global file that is being used for every innovation of commands with the CLI. This means whoever runs `cf login` last wins.

**Comment by ddgenome** [comment] 2018-03-08 12:19
"global file" meaning the home directory? You could try change the value of the `HOME` environment variable before running `cf`.

**Comment by claymccoy** [comment] 2018-03-09 04:51
I'm using [cf-client](https://www.npmjs.com/package/cf-client) to approximate what push does. I'm going to use the manifest.yml like push does. Apparently manifest.yml is not a base Cloud Foundry resource, but is created specifically for the CLI push. However, it seems like a nice convention so I'm just going to grab it and parse it myself and make use of the info in the more granular commands against the API.
I'm deploying apps manually with the CLI push, and I want to get the same result with what I do in the API. I need a small app that I can deploy over and over again. For some reason, I get errors when deploying black-duck-automation and pull-request-semantic-differ. That latter is really weird because it is running in CF now. I noticed some apps like ci-automation are running successfully, but I don't want to redeploy them. Any suggestions?

**Comment by jessitron** [comment] 2018-03-12 15:18
@claymccoy we can generate one quickly using `create spring` (running github-sdm) and then `add cloud foundry manifest`

**Comment by claymccoy** [comment] 2018-03-12 15:24
I was having issues withall the automation clients that I tried to deploy over the weekend, and not getting any actionable error messages in the PCF log. I am using this now, which deploys fine with the cli push:
https://github.com/claymccoy/hello-node_js-express

I think I am close to getting it to deploy with the API, but it turns out the "push" is not trivial to recreate against the API (even once you have some educated guesses about what it should do).

**Comment by claymccoy** [comment] 2018-03-14 17:20
Everything should be working except, after I upload the bits for the app and restart it, it doesn't build and stage the new bits. It just starts up the same old app. Why doesn't it do anything with the new bits? It isn't my test app, it deploys fine with CLI push.
I asked the guys in the #capi channel of the cloud_foundry slack. They were stumped too. The confirmed that there is no build command that I could kick off, and it can be tricky to understand why your new bits don't get built because it isn't under your control.
They had some recomendations. First, they recommended that I switch to the v3 API which does have a build command.
https://github.com/cloudfoundry/cloud_controller_ng/wiki/How-to-Create-an-App-Using-V3-of-the-CC-API
They also recommended running `cf push -v` to see all the api calls that it makes, and `cf v3-push -v` to understand what v3 is doing.

So, now I will look through the logs of `cf push -v` to determine if there is any quick fix I can change with my logic. But I'm likely going to have to take their recommendation and switch to the v3 calls. It means not using any of the js clients because they all use v2, but I understand the auth and API usage well enough at this point that it is not a problem.

**Comment by jessitron** [comment] 2018-03-14 18:41
wow. Thank you for your tenacity on this.

**Comment by claymccoy** [comment] 2018-03-23 03:25
In my tests I have been deploying node apps, which seems to work fine. I'm now testing it with deploying Spring apps, which are a little different. So the deployer needs to know what it is deploying (I guess based on the build pack) and behave differently. Specifically, a node app can have it's source code uploaded, but a java app needs the jar uploaded.

**Comment by cdupuis** [comment] 2018-04-04 23:04
I'm closing this as I think this is now in master. @claymccoy please re-open if that's not the case.

**Closed by cdupuis** 2018-04-04 23:04 UTC
Labels: bug, demo, release:bear

**Comment by claymccoy** [comment] 2018-04-05 01:12
Sorry, I thought we closed this one in the sdm meeting yesterday.
